name: when_scars_become_art
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  cloud_functions: ^5.6.2
  flutter_localizations:
    sdk: flutter
  firebase_core: ^3.6.0
  firebase_storage: ^12.3.0
  firebase_database: ^11.1.0
  firebase_auth: ^5.3.1
  audioplayers: ^6.1.0
  google_sign_in: ^6.2.1
  image_picker: ^1.1.2
  flutter_svg: ^2.0.10
  intl: ^0.20.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icons/logo.png
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/music/
    - assets/images/flags/
    - assets/messages/
